// Rotate one editor's password. Replaces scripts/seed-editors.ts, which
// took the whole roster as plaintext in an ADMIN_USERS env var
// ("user:pass,user:pass") — a format inherited from the pre-Postgres site
// that meant every editor's real password sat in Vercel's env config, in
// shell history, and in whatever chat it was pasted into. The roster
// itself now lives in a migration (drizzle/0005_editorial_team_accounts.sql,
// hashes only); this script exists for the one job that genuinely needs a
// CLI: rotating a single password after the fact.
//
// The new password is generated here, printed ONCE to stdout, and never
// written anywhere — only its bcrypt hash reaches the database. There is
// deliberately no way to pass a chosen password in: that's what makes
// "plaintext never persists" true by construction rather than by
// discipline.
//
// Usage: POSTGRES_URL=... npx tsx scripts/reset-editor-password.ts <username>

import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import { eq } from 'drizzle-orm';
import { db } from '../lib/db/client';
import { editors } from '../lib/db/schema';

// Ambiguous glyphs (l/1, O/0, I) are excluded on purpose: these passwords
// get read off a screen and retyped by a person at least once.
const LOWER = 'abcdefghijkmnopqrstuvwxyz';
const UPPER = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
const DIGIT = '23456789';
const SYM = '!@#$%^&*()-_=+[]{}?;:,.<>';

// Rejection sampling rather than `% alphabet.length` on a raw byte — the
// naive modulo biases toward the first (256 % len) characters of the
// alphabet, which quietly costs entropy in exactly the place it matters.
function pick(alphabet: string): string {
  const max = 256 - (256 % alphabet.length);
  for (;;) {
    const b = crypto.randomBytes(1)[0];
    if (b < max) return alphabet[b % alphabet.length];
  }
}

function shuffle<T>(arr: T[]): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = crypto.randomInt(i + 1);
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// Length is randomised too (20-26), so two passwords generated by this
// script never share a recognisable shape — the requirement was a
// 16-character minimum with no reused pattern across users, and a fixed
// "always exactly N, always symbol-in-position-3" template would satisfy
// the letter of that while failing its intent.
export function generatePassword(): string {
  const length = 20 + crypto.randomInt(7);
  const required = [pick(LOWER), pick(UPPER), pick(DIGIT), pick(SYM), pick(SYM), pick(DIGIT)];
  const all = LOWER + UPPER + DIGIT + SYM;
  while (required.length < length) required.push(pick(all));
  return shuffle(required).join('');
}

async function main() {
  const username = String(process.argv[2] || '').trim().toLowerCase();
  if (!username) {
    console.error('Usage: npx tsx scripts/reset-editor-password.ts <username>');
    process.exit(1);
  }

  const [editor] = await db.select().from(editors).where(eq(editors.username, username)).limit(1);
  if (!editor) {
    console.error(`[reset-editor-password] no editor named "${username}".`);
    console.error('Existing editors:');
    const all = await db.select({ username: editors.username }).from(editors);
    all.forEach(e => console.error(`  - ${e.username}`));
    process.exit(1);
  }

  const password = generatePassword();
  // Cost 12, matching auth.ts's verification side and
  // lib/actions/team.ts's acceptInvitation — a mismatch here wouldn't
  // break login (the cost is encoded in the hash itself) but would make
  // this account's verification cheaper than everyone else's.
  const passwordHash = await bcrypt.hash(password, 12);
  await db.update(editors).set({ passwordHash }).where(eq(editors.username, username));

  console.log('');
  console.log(`  usuario:    ${editor.username}`);
  console.log(`  contraseña: ${password}`);
  console.log('');
  console.log('  Se muestra una sola vez — solo se guardó el hash. Compártela por un canal seguro.');
  console.log('');
  process.exit(0);
}

main().catch(err => {
  console.error('[reset-editor-password] failed:', err);
  process.exit(1);
});
